# Generated by Django 5.0.6 on 2024-07-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_analysis', '0002_pcapfile_delete_idsalert_delete_networkpacket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packets', models.JSONField()),
                ('pcap_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traffic_analysis.pcapfile')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.DateTimeField(max_length=100)),
                ('destination_ip', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=50)),
                ('payload', models.TextField()),
                ('pcap_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_analysis.pcapfile')),
            ],
        ),
    ]
